micronaut:
  application:
    name: publisherLivro
  server:
    port: 8081
  cors:
    eneable: true

endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS

nats.addresses:
- nats://localhost:4222
